# Table of Contents
 <p>

In [20]:
#import sys
#sys.path.append('..')
from spikeHelper.loadSpike import loadSpikeBehav
import numpy as np
from scipy.io import loadmat
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
spk, bhv = loadSpikeBehav('Data/rato7tudo.mat')

In [13]:
ISI = spk.times.apply(np.unique).apply(np.diff)

In [14]:
ISIgc = ISI.iloc[np.nonzero(loadmat('Data/gcells_R7_2.mat')['gcelR7'].ravel())]

In [27]:
pd.DataFrame({i: pd.Series(v) for i,v in enumerate(ISIgc)})

0         1           2         3         4         5   \
0        5.857608  0.008438    1.169695  0.010936  0.008438  0.005243   
1        3.827343  0.043950    0.484598  0.043581  0.046080  0.005079   
2        0.669860  0.003850    0.261693  0.002703  0.015934  0.002294   
3        0.585236  0.025395    2.706309  0.025190  0.003113  0.008643   
4        0.691118  0.036536   39.878738  0.029246  0.008315  0.022487   
5      171.856241  0.033178    0.349102  0.048169  0.002253  0.004342   
6        0.372818  0.036127    1.248010  0.012820  0.004014  0.003318   
7        0.121283  0.013927    0.012616  0.014910  0.014459  0.003154   
8        0.583844  0.009912    0.407839  0.020931  0.009011  0.006062   
9        0.066355  0.030515  171.761664  0.014868  0.005243  0.012861   
10       0.001884  0.068035    0.262881  0.006144  0.001638  0.016015   
11       0.823378  0.192020    2.303795  0.020070  0.002007  0.011141   
12       0.385597  0.078274    1.298186  0.010404  0.008397  0.011100   
13       0.013803  0.254976    0.634225  0.002621  0.008397  0.004096   
14       0.103178  0.774267   16.069919  0.035635  0.015811  0.005816   
15       0.164741  0.013230    0.834929  0.009257  0.002703  0.006349   
16       0.417505  0.011387    0.164618  0.004628  0.002212  0.004137   
17       0.068198  0.035512    0.298885  0.049152  0.007864  0.007291   
18       0.503112  0.013066    0.248300  0.024576  0.022692  0.005079   
19       0.293437  0.060006   12.008940  0.002171  0.012001  0.004874   
20       0.146104  0.011796    0.646595  0.023061  0.001434  0.006308   
21       0.039199  0.007455    4.122542  0.049971  0.006431  0.011264   
22       0.545833  0.009953    1.161871  0.037765  0.001393  0.001720   
23       0.175719  0.002908    0.001679  0.014008  0.019661  0.018965   
24      15.286149  0.001720    0.174162  0.014172  0.003031  0.012861   
25       0.147006  0.006267    0.014868  0.044196  0.004506  0.012042   
26       0.094126  0.002990    7.068467  0.027607  0.002253  0.009953   
27       0.153395  0.002458    0.057139  0.018473  0.005816  0.001474   
28       0.073155  0.011182    0.195092  0.004628  0.002294  0.005653   
29       0.096051  0.004915    3.388375  0.014254  0.002294  0.020070   
...           ...       ...         ...       ...       ...       ...   
67871         NaN       NaN         NaN       NaN       NaN       NaN   
67872         NaN       NaN         NaN       NaN       NaN       NaN   
67873         NaN       NaN         NaN       NaN       NaN       NaN   
67874         NaN       NaN         NaN       NaN       NaN       NaN   
67875         NaN       NaN         NaN       NaN       NaN       NaN   
67876         NaN       NaN         NaN       NaN       NaN       NaN   
67877         NaN       NaN         NaN       NaN       NaN       NaN   
67878         NaN       NaN         NaN       NaN       NaN       NaN   
67879         NaN       NaN         NaN       NaN       NaN       NaN   
67880         NaN       NaN         NaN       NaN       NaN       NaN   
67881         NaN       NaN         NaN       NaN       NaN       NaN   
67882         NaN       NaN         NaN       NaN       NaN       NaN   
67883         NaN       NaN         NaN       NaN       NaN       NaN   
67884         NaN       NaN         NaN       NaN       NaN       NaN   
67885         NaN       NaN         NaN       NaN       NaN       NaN   
67886         NaN       NaN         NaN       NaN       NaN       NaN   
67887         NaN       NaN         NaN       NaN       NaN       NaN   
67888         NaN       NaN         NaN       NaN       NaN       NaN   
67889         NaN       NaN         NaN       NaN       NaN       NaN   
67890         NaN       NaN         NaN       NaN       NaN       NaN   
67891         NaN       NaN         NaN       NaN       NaN       NaN   
67892         NaN       NaN         NaN       NaN       NaN       NaN   
67893         NaN       NaN         NaN       NaN       NaN       NaN   


In [25]:
[i for i in ISIgc]

[array([ 5.8576076 ,  3.82734346,  0.66985989, ...,  0.24453115,
         0.66441226,  0.14626813]),
 array([ 0.00843763,  0.04395008,  0.00385022, ...,  0.11943936,
         0.02392077,  0.02932715]),
 array([ 1.16969466,  0.48459792,  0.26169324, ...,  1.53264117,
         0.54218769,  1.52588272]),
 array([ 0.0109365 ,  0.04358149,  0.00270319, ...,  0.0109365 ,
         0.0620544 ,  0.10055661]),
 array([ 0.00843787,  0.04607987,  0.01593351, ...,  0.91942906,
         0.11841536,  0.07299089]),
 array([  5.24282455e-03,   5.07903099e-03,   2.29382515e-03, ...,
          3.51518631e-01,   4.39672828e+00,   6.04897261e-01]),
 array([  0.5657804 ,  32.92749834,   5.90057468, ...,   0.21413875,
          0.91942906,   0.11841536]),
 array([  0.85651469,  37.61729527,   4.87071753, ...,   1.034199  ,
          1.59735823,   0.54845428]),
 array([ 0.37457919,  0.12406778,  0.027771  , ...,  1.15847182,
         0.4388864 ,  0.54845428]),
 array([ 0.09924626,  1.40103674,  0.19120121, ..

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=uint8)